# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hook
repos:
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.4.3
    hooks:
    -   id: autopep8
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: flake8
    -   id: check-ast
    -   id: check-builtin-literals
    -   id: check-added-large-files
